class Character():
    def __init__(self,name,age,dialogues):
            self.name=name
            self.age=age
            self.dialogues=dialogues
class Elite_Character(Character):
    def __init__(self, name, age, dialogues,theme):
        super().__init__(name, age, dialogues)
        self.theme=theme
character1=Character(name="Maxim",age=17,dialogues=["more deep fried goodies please, but 'don't tell Misha" ,"everyone else is joining the numbers but what about me","more responsibilites ah man","oh man i should have finished those deep fried chicken wings from lash nigh ah! , im starving"])
character2=Character(name="Alok",age=28,dialogues=["Feel the pressure to feel the energy","i gonna be so bigger"])
character2e=Elite_Character(name="Awakened Alok",age=28,dialogues=["Beats with healing power can cure your hot","Love Make All The Difference","Make YOur Sound Louder"],theme="Alok Awakening")
character3=Character(name="Skyler",age=26,dialogues=["don't forget me im top of the MTP"])
character4=Character(name="Chrono",age=35,dialogues=["Don't Trust Miracles Trust Me","You and me were a team","Join the battle be the legend","To Be The Best You Need The Best"])
character5=Character(name="K",age=31,dialogues=["One Step Closer To Enlightment","It's all in The Mind","Some Peoples Are The Prisoners Of Their Own Mind"])

character6=Character(name="Hayato",age=20,dialogues=["Time Is A Slice Of Dice","Everything For The Family","Patience Is A virtue","Commit My Blade"])
character6e=Elite_Character(name="Hayato \"Firebrand\"",age=20,dialogues=["On My Fist Or My Blade","A Fire Reages Within Me","Get Too Close And You Might Get Burnt",],theme="Firebrand")
character7=Character(name="Moco",age=20,dialogues=["Can I Trust You On This","Connection Established ,Can you hear me.","Some where some day there will be termines For Human Beings But Not Today","We all deserve the truth"])
character7e=Elite_Character(name="Moco \"Enigma\"",age=20,dialogues=["A new dawn of civilization shall come after this endless night","im going up against the world do you still wanna join me?","Is this what you want Leonard","This is the battle is must pick"])
character8=Character(name="Misha",age=19,dialogues=[])
character9=Character(name="Kelly",age=17,dialogues=["Let's Worm Up","I love feeling the wind in my hair","Another Lap Completed"])
character9e=Elite_Character(name="Kelly \"The Swift\"",age=17,dialogues=["i will leave you in the dust","im going for gold", "im fast, im really fast","don't underestimate me"],theme="Booyah Day 2020")
character10=Character(name="Suzy",age=19,dialogues=["Hunting bounties salvage in souls","the price of faith is my bounty","the stelth accuracy my signature moves","Every Mission has a price are you ready to pay?"])
character11=Character(name="Sonia",age=20,dialogues=["The Future belongs to nanotechnology","Adapting To Change Is The nature of Evolution","i will take over horizon its my destiny","I have a vision and i will achieve it"])
character12=Character(name="Orion",age=22,dialogues=["that's an easy im the best killer around","From now i will do what ever i want","no prison can hold me now","If they think im a monster i will give them a monster"])
character13=Character(name="Tatsuya",age=16,dialogues=["Boom Boom dash-dash i will always be faster","Don't Believe Shirou ","i just borrowed Shirou's Shoes for something, you wanna join?"])
character14=Character(name="Luna",age=28,dialogues=["i didn't choose to lead leadership choose me","I won't let you suffer","i protect those that needed"])
character15=Character(name="J.Biebs",age=28,dialogues=["Big things can come from small beginnings","its time for us to reunite","Time to put soul into words","Let me sing you the story of you"])
character15=Character(name="Olivia",age=29,dialogues=[])
character16=Character(name="Ford",age=29,dialogues=["My Healing Skills Would Help Me"])
character17=Character(name="Xayne",age=23,dialogues=["im all adrenaline","faling is freedom","chase me if you can","stretch your wings and fly"])
character18=Character(name="Alvaro",age=26,dialogues=["Can You feel the burn of Desire","Can't for everyone to see my explosive surprise","boom im explosive","from the asses i rise"])
character19=Character(name="Andrew",age=42,dialogues=["Protect Those you love","No Crime NO Problem","you do what you have to",])
character20=Character(name="Shani",age=31,dialogues=[])
character21=Character(name="Wolfrahh",age=19,dialogues=["loff well loff","im the leader of the park","alfa war baby","my bonut is worst than my bike"])
character22=Character(name="Notora",age=27,dialogues=["Let's go both renold","a challege ha!","all you see is the back of my jacket","go faster go home"])
character23=Character(name="Kapella",age=21,dialogues=["keep climbing those skills","whose comming to my concert","i will put a little week into you","La-la la la"])
character24=Character(name="A124",age=4,dialogues=[])
character25=Character(name="Luquetta",age=20,dialogues=["need me to kick something","top goal scrorer at your service","you have to score your goals","my friend call me hattrick"])
character26=Character(name="Steffie",age=23,dialogues=["spray parinting is my art","my friends call me the rebel", "eye's are just useless when the mind is blind.","don't let anyone tell you what you can do"])
character27=Character(name="Maro",age=32,dialogues=["fly in the sky to search for prey","im a bird of prey","sharp close cut the deep ely"])
character28=Character(name="Jota",age=31,dialogues=["Hantamreka","parkour is the name of my game","there are no limit only obstacles","i will keep on climbing higher"])
character29=Character(name="Jai",age=30,dialogues=["im the fists of the law", "you been know the truth","hard work pays off","i never miss a fight","i bring you the truth"])
character30=Character(name="Nikita",age=22,dialogues=[])
character31=Character(name="Miguel",age=29,dialogues=[])
character32=Character(name="Shirou",age=19,dialogues=["competetion im the competetion","roses in cuts would help you improve"," im the hurricane"])
character33=Character(name="Caroline",age=17,dialogues=[])
character34=Character(name="Dimitri",age=26,dialogues=["lets get this party started","bounce to my beat","take it to a higher level"])
character35=Character(name="Antonio",age=30,dialogues=[])
character36=Character(name="Laura",age=29,dialogues=[])
character37=Character(name="Thiva",age=25,dialogues=["music is the soul of the heart","agresando of the track","rock to the rythm"])
character38=Character(name="Leon",age=26,dialogues=["i can outjump you with only on leg","responsibility is on my shoulders","watch out my dance","leu"])
character39=Character(name="Clu",age=24,dialogues=["keep following the evidence","what mystery do you need me to solve","don't worry im on the case","anyone got a clue."])
character40=Character(name="Dasha",age=25,dialogues=["once i start you can't stop me","let's get the party started","oh! do you need to prank"])
character41=Character(name="Paloma",age=28,dialogues=[])
character42=Character(name="Rafael",age=31,dialogues=[])
character43=Character(name="Wukong",age=00,dialogues=["heehehhehehehhhe"])
character44=Character(name="Kenta",age=38,dialogues=["duty always comes first i learnt my lesson","guarding young master hayato is no easy task","i swear to serve for yagami's my blade is this"])
character45=Character(name="Homer",age=30,dialogues=["the members only cause is trouble","life is about overcoming obstackles what have you overcome lately","i have start the techies maybe, its time for me to start anothe story","I never dreamed i would be the key to leaving guiza"])
character46=Character(name="Santino",age=34,dialogues=["watch me go viral","the best way to say another day stay safe","sometimes you need to chase your dreams to be happy","you know those angelic pants those were my designs"])
character47=Character(name="D-Bee",age=19,dialogues=["follow my moves","ah- ha spin a way spin my when dance to it","get your body moving","from twist to hand stands"])